version: '3'
services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
  server:
    depends_on:
      - db
    build: ./server
    environment:
      # La connessione avviene come admin per facilitare l'avvio
      MONGO_STRING: mongodb://user:password@db:27017/bookmarks?authSource=admin
    ports:
      - '8081:8081'
